import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Inter } from "next/font/google";
// redux
import { store } from "@/redux/store";
import { Providers } from "@/redux/provider";
// Theme
import { ThemeContext } from "@/theme/ThemeContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeContext>
        <body
          className={inter.className}
          style={{ background: "background.default" }}
        >
          <Toaster />
          <Providers store={store}>{children}</Providers>
        </body>
      </ThemeContext>
    </html>
  );
}
